### ISSUE TITLE
Init failed

### ISSUE THREAD

**Issue by brdacon1** [joaodematejr/SmartL400#1]
Olá estou tendo problemas na tentativa de comunicação com a impressora da maquina estou obtendo o erro: Init failed
Como consigo obter um aar mais atual?

**Comment by joaodematejr** [comment]
Precisa entrar em contato com a Positivo para obter o aar mais atualizado.

**Comment by brdacon1** [comment]
Tem o contato de lá Joao? Como vc conseguiu obter o aar?

**Comment by joaodematejr** [comment]
> Tem o contato de lá Joao? Como vc conseguiu obter o aar?

https://www.positivotecnologia.com.br/fale-conosco/

aar foi enviado junto com a pos quando fui fazer a homologação da REDE

**Comment by brdacon1** [comment]
Cara muito obrigado de coração, enviei uma mensagem pedindo.
